[project]
name = "diffome"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dipy>=1.11.0",
    "gudhi>=3.11.0",
    "matplotlib>=3.10.5",
    "nibabel>=5.3.2",
]
